[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]

[lib]
name = "kernel"
path = "src/lib.rs"
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"