[package]
name = "stm32l552"
version = "0.1.0"
edition = "2021"

[dependencies]
peripheral_regs = { path = "../../common/peripheral_regs" }
memory_layout = { path = "../../common/memory_layout" }
memory_protection_server = { path = "../../kernel/memory_protection_server" }