[target.thumbv8m.main-none-eabihf]
rustflags = [
  "-C", "linker=/opt/gcc-arm-none-eabi/bin/arm-none-eabi-ld",
  "-C", "link-arg=-T../linker/platform.ld"
]
[build]
target = "thumbv8m.main-none-eabihf"
